#!/bin/bash
echo "Waiting for curl pod to become ready..."
kubectl wait --for condition=Ready pods -l=app=curl

node=$(kubectl get pod curl -o json | jq -r .spec.nodeName)

echo "Running on node: ${node}"

echo "-----------------------------------------------------------------"
echo "Before:"
kubectl get pod curl -o wide
kubectl get cep curl
echo "-----------------------------------------------------------------"

docker exec ${node} rm -rf /etc/cni/net.d/05-cilium.conf /run/cilium/state

docker stop ${node}
docker start ${node}

kubectl wait --for condition=Unknown pods -l=app=curl
kubectl wait --for condition=Ready pods -l=app=curl

echo "-----------------------------------------------------------------"
echo "After:"
kubectl get pod curl -o wide
kubectl get cep curl
echo "-----------------------------------------------------------------"

