// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: events.proto
// Original file comments:
// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium
//
#ifndef GRPC_events_2eproto__INCLUDED
#define GRPC_events_2eproto__INCLUDED

#include "events.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace events {

class FlightRecorder final {
 public:
  static constexpr char const* service_full_name() {
    return "events.FlightRecorder";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // GetStatus returns streams all current status updates, following this
    // it will stream all future status updates.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::events::StatusUpdateEvent>> GetStatus(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::events::StatusUpdateEvent>>(GetStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::events::StatusUpdateEvent>> AsyncGetStatus(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::events::StatusUpdateEvent>>(AsyncGetStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::events::StatusUpdateEvent>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::events::StatusUpdateEvent>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // GetStatus returns streams all current status updates, following this
      // it will stream all future status updates.
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetStatus(::grpc::ClientContext* context, ::events::StatusUpdateRequest* request, ::grpc::ClientReadReactor< ::events::StatusUpdateEvent>* reactor) = 0;
      #else
      virtual void GetStatus(::grpc::ClientContext* context, ::events::StatusUpdateRequest* request, ::grpc::experimental::ClientReadReactor< ::events::StatusUpdateEvent>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::events::StatusUpdateEvent>* GetStatusRaw(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::events::StatusUpdateEvent>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::events::StatusUpdateEvent>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::events::StatusUpdateEvent>> GetStatus(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::events::StatusUpdateEvent>>(GetStatusRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::events::StatusUpdateEvent>> AsyncGetStatus(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::events::StatusUpdateEvent>>(AsyncGetStatusRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::events::StatusUpdateEvent>> PrepareAsyncGetStatus(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::events::StatusUpdateEvent>>(PrepareAsyncGetStatusRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetStatus(::grpc::ClientContext* context, ::events::StatusUpdateRequest* request, ::grpc::ClientReadReactor< ::events::StatusUpdateEvent>* reactor) override;
      #else
      void GetStatus(::grpc::ClientContext* context, ::events::StatusUpdateRequest* request, ::grpc::experimental::ClientReadReactor< ::events::StatusUpdateEvent>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::events::StatusUpdateEvent>* GetStatusRaw(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request) override;
    ::grpc::ClientAsyncReader< ::events::StatusUpdateEvent>* AsyncGetStatusRaw(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::events::StatusUpdateEvent>* PrepareAsyncGetStatusRaw(::grpc::ClientContext* context, const ::events::StatusUpdateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // GetStatus returns streams all current status updates, following this
    // it will stream all future status updates.
    virtual ::grpc::Status GetStatus(::grpc::ServerContext* context, const ::events::StatusUpdateRequest* request, ::grpc::ServerWriter< ::events::StatusUpdateEvent>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetStatus() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/, ::grpc::ServerWriter< ::events::StatusUpdateEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::events::StatusUpdateRequest* request, ::grpc::ServerAsyncWriter< ::events::StatusUpdateEvent>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetStatus<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetStatus() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::events::StatusUpdateRequest, ::events::StatusUpdateEvent>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::events::StatusUpdateRequest* request) { return this->GetStatus(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/, ::grpc::ServerWriter< ::events::StatusUpdateEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::events::StatusUpdateEvent>* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::events::StatusUpdateEvent>* GetStatus(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetStatus<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetStatus<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetStatus() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/, ::grpc::ServerWriter< ::events::StatusUpdateEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetStatus() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/, ::grpc::ServerWriter< ::events::StatusUpdateEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetStatus() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->GetStatus(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/, ::grpc::ServerWriter< ::events::StatusUpdateEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* GetStatus(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetStatus() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::events::StatusUpdateRequest, ::events::StatusUpdateEvent>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerSplitStreamer<
                     ::events::StatusUpdateRequest, ::events::StatusUpdateEvent>* streamer) {
                       return this->StreamedGetStatus(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetStatus(::grpc::ServerContext* /*context*/, const ::events::StatusUpdateRequest* /*request*/, ::grpc::ServerWriter< ::events::StatusUpdateEvent>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetStatus(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::events::StatusUpdateRequest,::events::StatusUpdateEvent>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetStatus<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetStatus<Service > StreamedService;
};

}  // namespace events


#endif  // GRPC_events_2eproto__INCLUDED
