// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MapEventLogMetadata Metadata about a MapEventLog
//
// swagger:model MapEventLogMetadata
type MapEventLogMetadata struct {

	// buffer size
	BufferSize int64 `json:"bufferSize,omitempty"`

	// map
	Map string `json:"map,omitempty"`
}

// Validate validates this map event log metadata
func (m *MapEventLogMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MapEventLogMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MapEventLogMetadata) UnmarshalBinary(b []byte) error {
	var res MapEventLogMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
