// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetMapIDEventsHandlerFunc turns a function with the right signature into a get map ID events handler
type GetMapIDEventsHandlerFunc func(GetMapIDEventsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMapIDEventsHandlerFunc) Handle(params GetMapIDEventsParams) middleware.Responder {
	return fn(params)
}

// GetMapIDEventsHandler interface for that can handle valid get map ID events params
type GetMapIDEventsHandler interface {
	Handle(GetMapIDEventsParams) middleware.Responder
}

// NewGetMapIDEvents creates a new http.Handler for the get map ID events operation
func NewGetMapIDEvents(ctx *middleware.Context, handler GetMapIDEventsHandler) *GetMapIDEvents {
	return &GetMapIDEvents{Context: ctx, Handler: handler}
}

/*GetMapIDEvents swagger:route GET /map/{id}/events endpoint getMapIdEvents

Retrieves the status logs associated with this endpoint.

*/
type GetMapIDEvents struct {
	Context *middleware.Context
	Handler GetMapIDEventsHandler
}

func (o *GetMapIDEvents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMapIDEventsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
