// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package endpoint

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/cilium/api/v1/models"
)

// GetMapIDEventsOKCode is the HTTP code returned for type GetMapIDEventsOK
const GetMapIDEventsOKCode int = 200

/*GetMapIDEventsOK Success

swagger:response getMapIdEventsOK
*/
type GetMapIDEventsOK struct {

	/*
	  In: Body
	*/
	Payload models.EndpointStatusLog `json:"body,omitempty"`
}

// NewGetMapIDEventsOK creates GetMapIDEventsOK with default headers values
func NewGetMapIDEventsOK() *GetMapIDEventsOK {

	return &GetMapIDEventsOK{}
}

// WithPayload adds the payload to the get map Id events o k response
func (o *GetMapIDEventsOK) WithPayload(payload models.EndpointStatusLog) *GetMapIDEventsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get map Id events o k response
func (o *GetMapIDEventsOK) SetPayload(payload models.EndpointStatusLog) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMapIDEventsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.EndpointStatusLog{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetMapIDEventsInvalidCode is the HTTP code returned for type GetMapIDEventsInvalid
const GetMapIDEventsInvalidCode int = 400

/*GetMapIDEventsInvalid Invalid identity provided

swagger:response getMapIdEventsInvalid
*/
type GetMapIDEventsInvalid struct {
}

// NewGetMapIDEventsInvalid creates GetMapIDEventsInvalid with default headers values
func NewGetMapIDEventsInvalid() *GetMapIDEventsInvalid {

	return &GetMapIDEventsInvalid{}
}

// WriteResponse to the client
func (o *GetMapIDEventsInvalid) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetMapIDEventsNotFoundCode is the HTTP code returned for type GetMapIDEventsNotFound
const GetMapIDEventsNotFoundCode int = 404

/*GetMapIDEventsNotFound Endpoint not found

swagger:response getMapIdEventsNotFound
*/
type GetMapIDEventsNotFound struct {
}

// NewGetMapIDEventsNotFound creates GetMapIDEventsNotFound with default headers values
func NewGetMapIDEventsNotFound() *GetMapIDEventsNotFound {

	return &GetMapIDEventsNotFound{}
}

// WriteResponse to the client
func (o *GetMapIDEventsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetMapIDEventsTooManyRequestsCode is the HTTP code returned for type GetMapIDEventsTooManyRequests
const GetMapIDEventsTooManyRequestsCode int = 429

/*GetMapIDEventsTooManyRequests Rate-limiting too many requests in the given time frame

swagger:response getMapIdEventsTooManyRequests
*/
type GetMapIDEventsTooManyRequests struct {
}

// NewGetMapIDEventsTooManyRequests creates GetMapIDEventsTooManyRequests with default headers values
func NewGetMapIDEventsTooManyRequests() *GetMapIDEventsTooManyRequests {

	return &GetMapIDEventsTooManyRequests{}
}

// WriteResponse to the client
func (o *GetMapIDEventsTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(429)
}
